### ISSUE TITLE
ln not recognized as log

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#39]
![image](https://github.com/herbie-fp/odyssey/assets/8119219/789ce75c-a988-4233-9c4c-20bba6543cb1)

Error: Error sending data to Herbie server at http://127.0.0.1:8000/api/sample:
Herbie server: Invalid program
  web::38: Unknown operator ln
See <https://herbie.uwplse.org/doc/2.0/faq.html#invalid-syntax> for more.

    at c (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/misback/.vscode/extensions/herbie-fp.odyssey-fp-1.0.4/dist/webview.bundle.js:2:1256127)
    at async Object.getSample (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/misback/.vscode/extensions/herbie-fp.odyssey-fp-1.0.4/dist/webview.bundle.js:2:1231181)
    at async https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/misback/.vscode/extensions/herbie-fp.odyssey-fp-1.0.4/dist/webview.bundle.js:2:1233871

**Comment by elmisback** [comment]
This issue is more serious since it occurs in our asinh demo and there is no warning about ln in the spec entry!

**Comment by elmisback** [comment]
I've hacked this so that `ln` just looks like `log` to Herbie rather than crashing. This is not technically correct and we should warn the user in this case!

**Comment by elmisback** [comment]
Nvm `log` is natural log for Herbie and we now explain this on the landing page, closing.
